/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsSlugRouteImport } from './routes/rooms.$slug'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated/staff.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account.index'
import { Route as AuthenticatedStaffChecklistRouteImport } from './routes/_authenticated/staff.checklist'
import { Route as AuthenticatedStaffCalendarRouteImport } from './routes/_authenticated/staff.calendar'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminCalendarSyncRouteImport } from './routes/_authenticated/admin.calendar-sync'
import { Route as AuthenticatedAdminCalendarRouteImport } from './routes/_authenticated/admin.calendar'
import { Route as AuthenticatedAdminRoomsIndexRouteImport } from './routes/_authenticated/admin.rooms.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as AuthenticatedStaffEventsIdRouteImport } from './routes/_authenticated/staff.events.$id'
import { Route as AuthenticatedAdminBookingsIdRouteImport } from './routes/_authenticated/admin.bookings.$id'
import { Route as AuthenticatedAccountBookingsIdRouteImport } from './routes/_authenticated/account.bookings.$id'
import { Route as ApiPublicCalendarTokenFeedDoticsRouteImport } from './routes/api/public/calendar.$token.feed[.]ics'
import { Route as AuthenticatedAdminRoomsIdMediaRouteImport } from './routes/_authenticated/admin.rooms.$id.media'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsSlugRoute = RoomsSlugRouteImport.update({
  id: '/rooms/$slug',
  path: '/rooms/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedStaffRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const AuthenticatedStaffChecklistRoute =
  AuthenticatedStaffChecklistRouteImport.update({
    id: '/checklist',
    path: '/checklist',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedStaffCalendarRoute =
  AuthenticatedStaffCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarSyncRoute =
  AuthenticatedAdminCalendarSyncRouteImport.update({
    id: '/calendar-sync',
    path: '/calendar-sync',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCalendarRoute =
  AuthenticatedAdminCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRoomsIndexRoute =
  AuthenticatedAdminRoomsIndexRouteImport.update({
    id: '/rooms/',
    path: '/rooms/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedStaffEventsIdRoute =
  AuthenticatedStaffEventsIdRouteImport.update({
    id: '/events/$id',
    path: '/events/$id',
    getParentRoute: () => AuthenticatedStaffRoute,
  } as any)
const AuthenticatedAdminBookingsIdRoute =
  AuthenticatedAdminBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAccountBookingsIdRoute =
  AuthenticatedAccountBookingsIdRouteImport.update({
    id: '/bookings/$id',
    path: '/bookings/$id',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiPublicCalendarTokenFeedDoticsRoute =
  ApiPublicCalendarTokenFeedDoticsRouteImport.update({
    id: '/api/public/calendar/$token/feed.ics',
    path: '/api/public/calendar/$token/feed.ics',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRoomsIdMediaRoute =
  AuthenticatedAdminRoomsIdMediaRouteImport.update({
    id: '/rooms/$id/media',
    path: '/rooms/$id/media',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/staff': typeof AuthenticatedStaffRouteWithChildren
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/calendar-sync': typeof AuthenticatedAdminCalendarSyncRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/calendar': typeof AuthenticatedStaffCalendarRoute
  '/staff/checklist': typeof AuthenticatedStaffChecklistRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/account/bookings/$id': typeof AuthenticatedAccountBookingsIdRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/rooms/': typeof AuthenticatedAdminRoomsIndexRoute
  '/admin/rooms/$id/media': typeof AuthenticatedAdminRoomsIdMediaRoute
  '/api/public/calendar/$token/feed.ics': typeof ApiPublicCalendarTokenFeedDoticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms': typeof RoomsIndexRoute
  '/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/admin/calendar-sync': typeof AuthenticatedAdminCalendarSyncRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/staff/calendar': typeof AuthenticatedStaffCalendarRoute
  '/staff/checklist': typeof AuthenticatedStaffChecklistRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/account/bookings/$id': typeof AuthenticatedAccountBookingsIdRoute
  '/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsIndexRoute
  '/admin/rooms/$id/media': typeof AuthenticatedAdminRoomsIdMediaRoute
  '/api/public/calendar/$token/feed.ics': typeof ApiPublicCalendarTokenFeedDoticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/quote': typeof QuoteRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/staff': typeof AuthenticatedStaffRouteWithChildren
  '/rooms/$slug': typeof RoomsSlugRoute
  '/rooms/': typeof RoomsIndexRoute
  '/_authenticated/admin/calendar': typeof AuthenticatedAdminCalendarRoute
  '/_authenticated/admin/calendar-sync': typeof AuthenticatedAdminCalendarSyncRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/staff/calendar': typeof AuthenticatedStaffCalendarRoute
  '/_authenticated/staff/checklist': typeof AuthenticatedStaffChecklistRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/account/bookings/$id': typeof AuthenticatedAccountBookingsIdRoute
  '/_authenticated/admin/bookings/$id': typeof AuthenticatedAdminBookingsIdRoute
  '/_authenticated/staff/events/$id': typeof AuthenticatedStaffEventsIdRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/admin/rooms/': typeof AuthenticatedAdminRoomsIndexRoute
  '/_authenticated/admin/rooms/$id/media': typeof AuthenticatedAdminRoomsIdMediaRoute
  '/api/public/calendar/$token/feed.ics': typeof ApiPublicCalendarTokenFeedDoticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/quote'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/staff'
    | '/rooms/$slug'
    | '/rooms/'
    | '/admin/calendar'
    | '/admin/calendar-sync'
    | '/admin/settings'
    | '/staff/calendar'
    | '/staff/checklist'
    | '/account/'
    | '/admin/'
    | '/staff/'
    | '/account/bookings/$id'
    | '/admin/bookings/$id'
    | '/staff/events/$id'
    | '/lovable/email/queue/process'
    | '/admin/rooms/'
    | '/admin/rooms/$id/media'
    | '/api/public/calendar/$token/feed.ics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/quote'
    | '/sitemap.xml'
    | '/rooms/$slug'
    | '/rooms'
    | '/admin/calendar'
    | '/admin/calendar-sync'
    | '/admin/settings'
    | '/staff/calendar'
    | '/staff/checklist'
    | '/account'
    | '/admin'
    | '/staff'
    | '/account/bookings/$id'
    | '/admin/bookings/$id'
    | '/staff/events/$id'
    | '/lovable/email/queue/process'
    | '/admin/rooms'
    | '/admin/rooms/$id/media'
    | '/api/public/calendar/$token/feed.ics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/quote'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/staff'
    | '/rooms/$slug'
    | '/rooms/'
    | '/_authenticated/admin/calendar'
    | '/_authenticated/admin/calendar-sync'
    | '/_authenticated/admin/settings'
    | '/_authenticated/staff/calendar'
    | '/_authenticated/staff/checklist'
    | '/_authenticated/account/'
    | '/_authenticated/admin/'
    | '/_authenticated/staff/'
    | '/_authenticated/account/bookings/$id'
    | '/_authenticated/admin/bookings/$id'
    | '/_authenticated/staff/events/$id'
    | '/lovable/email/queue/process'
    | '/_authenticated/admin/rooms/'
    | '/_authenticated/admin/rooms/$id/media'
    | '/api/public/calendar/$token/feed.ics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  QuoteRoute: typeof QuoteRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RoomsSlugRoute: typeof RoomsSlugRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicCalendarTokenFeedDoticsRoute: typeof ApiPublicCalendarTokenFeedDoticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$slug': {
      id: '/rooms/$slug'
      path: '/rooms/$slug'
      fullPath: '/rooms/$slug'
      preLoaderRoute: typeof RoomsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/_authenticated/staff/checklist': {
      id: '/_authenticated/staff/checklist'
      path: '/checklist'
      fullPath: '/staff/checklist'
      preLoaderRoute: typeof AuthenticatedStaffChecklistRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/staff/calendar': {
      id: '/_authenticated/staff/calendar'
      path: '/calendar'
      fullPath: '/staff/calendar'
      preLoaderRoute: typeof AuthenticatedStaffCalendarRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar-sync': {
      id: '/_authenticated/admin/calendar-sync'
      path: '/calendar-sync'
      fullPath: '/admin/calendar-sync'
      preLoaderRoute: typeof AuthenticatedAdminCalendarSyncRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/calendar': {
      id: '/_authenticated/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AuthenticatedAdminCalendarRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rooms/': {
      id: '/_authenticated/admin/rooms/'
      path: '/rooms'
      fullPath: '/admin/rooms/'
      preLoaderRoute: typeof AuthenticatedAdminRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/staff/events/$id': {
      id: '/_authenticated/staff/events/$id'
      path: '/events/$id'
      fullPath: '/staff/events/$id'
      preLoaderRoute: typeof AuthenticatedStaffEventsIdRouteImport
      parentRoute: typeof AuthenticatedStaffRoute
    }
    '/_authenticated/admin/bookings/$id': {
      id: '/_authenticated/admin/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/admin/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAdminBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/bookings/$id': {
      id: '/_authenticated/account/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/account/bookings/$id'
      preLoaderRoute: typeof AuthenticatedAccountBookingsIdRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/calendar/$token/feed.ics': {
      id: '/api/public/calendar/$token/feed.ics'
      path: '/api/public/calendar/$token/feed.ics'
      fullPath: '/api/public/calendar/$token/feed.ics'
      preLoaderRoute: typeof ApiPublicCalendarTokenFeedDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/rooms/$id/media': {
      id: '/_authenticated/admin/rooms/$id/media'
      path: '/rooms/$id/media'
      fullPath: '/admin/rooms/$id/media'
      preLoaderRoute: typeof AuthenticatedAdminRoomsIdMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
  AuthenticatedAccountBookingsIdRoute: typeof AuthenticatedAccountBookingsIdRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  AuthenticatedAccountBookingsIdRoute: AuthenticatedAccountBookingsIdRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminCalendarRoute: typeof AuthenticatedAdminCalendarRoute
  AuthenticatedAdminCalendarSyncRoute: typeof AuthenticatedAdminCalendarSyncRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminBookingsIdRoute: typeof AuthenticatedAdminBookingsIdRoute
  AuthenticatedAdminRoomsIndexRoute: typeof AuthenticatedAdminRoomsIndexRoute
  AuthenticatedAdminRoomsIdMediaRoute: typeof AuthenticatedAdminRoomsIdMediaRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminCalendarRoute: AuthenticatedAdminCalendarRoute,
  AuthenticatedAdminCalendarSyncRoute: AuthenticatedAdminCalendarSyncRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminBookingsIdRoute: AuthenticatedAdminBookingsIdRoute,
  AuthenticatedAdminRoomsIndexRoute: AuthenticatedAdminRoomsIndexRoute,
  AuthenticatedAdminRoomsIdMediaRoute: AuthenticatedAdminRoomsIdMediaRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedStaffRouteChildren {
  AuthenticatedStaffCalendarRoute: typeof AuthenticatedStaffCalendarRoute
  AuthenticatedStaffChecklistRoute: typeof AuthenticatedStaffChecklistRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedStaffEventsIdRoute: typeof AuthenticatedStaffEventsIdRoute
}

const AuthenticatedStaffRouteChildren: AuthenticatedStaffRouteChildren = {
  AuthenticatedStaffCalendarRoute: AuthenticatedStaffCalendarRoute,
  AuthenticatedStaffChecklistRoute: AuthenticatedStaffChecklistRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedStaffEventsIdRoute: AuthenticatedStaffEventsIdRoute,
}

const AuthenticatedStaffRouteWithChildren =
  AuthenticatedStaffRoute._addFileChildren(AuthenticatedStaffRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedStaffRoute: AuthenticatedStaffRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  QuoteRoute: QuoteRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RoomsSlugRoute: RoomsSlugRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicCalendarTokenFeedDoticsRoute: ApiPublicCalendarTokenFeedDoticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
